# Generated by Django 5.2.2 on 2025-09-16 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название альбома')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='albums/covers/', verbose_name='Обложка')),
                ('release_date', models.DateField(verbose_name='Дата выпуска')),
                ('authors', models.CharField(max_length=255, verbose_name='Авторы')),
            ],
            options={
                'verbose_name': '💽 Альбом',
                'verbose_name_plural': '💽 Альбомы',
            },
        ),
        migrations.CreateModel(
            name='Countdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.DateTimeField(help_text='Дата и время окончания отсчёта', verbose_name='Конечное время')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Название счётчика')),
            ],
        ),
        migrations.CreateModel(
            name='SongInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название песни')),
                ('lyrics', models.TextField(verbose_name='Текст песни')),
                ('chords', models.TextField(help_text='Введите аккорды в текстовом формате', verbose_name='Аккорды песни')),
            ],
            options={
                'verbose_name': '🍓 Песня',
                'verbose_name_plural': '🍓 Аккорды песен',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название трека')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='tracks/covers/', verbose_name='Обложка')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='tracks/audio/', verbose_name='Аудиофайл (MP3)')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='botapp.album', verbose_name='Альбом')),
            ],
            options={
                'verbose_name': '🎼 Трек',
                'verbose_name_plural': '🎼 Треки',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_news', models.CharField(default='News', max_length=300)),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='news/photos/', verbose_name='Фото')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='botapp.track', verbose_name='Аудиотрек')),
            ],
            options={
                'verbose_name': '📰 Новость',
                'verbose_name_plural': '📰 Новости',
            },
        ),
    ]
