# Generated by Django 5.2.2 on 2025-09-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='is_movies',
            field=models.BooleanField(blank=True, default=False, verbose_name='В Кино'),
        ),
        migrations.AddField(
            model_name='track',
            name='is_popular',
            field=models.BooleanField(blank=True, default=False, verbose_name='Популярные'),
        ),
        migrations.AddField(
            model_name='track',
            name='is_tomorrow',
            field=models.BooleanField(blank=True, default=False, verbose_name='Завтра в эфире'),
        ),
    ]
