# Generated by Django 5.2.2 on 2025-09-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0002_track_is_movies_track_is_popular_track_is_tomorrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='is_main',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='На главную'),
        ),
    ]
