# Generated by Django 5.2.2 on 2025-09-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0003_track_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='is_main',
            field=models.BooleanField(blank=True, default=True, verbose_name='На главную'),
        ),
    ]
