# Generated by Django 5.2.2 on 2025-10-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0004_alter_track_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='is_tonight',
            field=models.BooleanField(blank=True, default=False, verbose_name='Сегодня в эфире'),
        ),
    ]
