# Generated by Django 5.2.2 on 2025-10-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0005_track_is_tonight'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='news/audio/', verbose_name='Аудио'),
        ),
    ]
