# Generated by Django 5.2.2 on 2025-10-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0006_news_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название видео')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('video_file', models.FileField(upload_to='videos/', verbose_name='Видео файл')),
            ],
            options={
                'verbose_name': '📹 Видео',
                'verbose_name_plural': '📹 Видео',
            },
        ),
    ]
